name: future_diary
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.4
  go_router: ^12.1.3
  google_sign_in: ^6.1.5
  googleapis: ^11.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/backgrounds/
      - assets/icons/
      - assets/illustrations/
      - assets/illustrations/intro/
  fonts:

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf

    - family: MaruBuri
      fonts:
        - asset: assets/fonts/MaruBuri-Regular.ttf
        - asset: assets/fonts/MaruBuri-Bold.ttf
        - asset: assets/fonts/MaruBuri-SemiBold.ttf
        - asset: assets/fonts/MaruBuri-ExtraLight.ttf
        - asset: assets/fonts/MaruBuri-Light.ttf

    - family: OnePrettyNight
      fonts:
        - asset: assets/fonts/Cafe24Oneprettynight-v2.0.ttf

    - family: Simplehae
      fonts:
        - asset: assets/fonts/Cafe24Simplehae-v2.0.ttf

    - family: DonGgukUniversity
      fonts:
        - asset: assets/fonts/DONGGUK UNIVERSITY.ttf

    - family: leeseoyoon
      fonts:
        - asset: assets/fonts/leeseoyoon.ttf

    - family: gyobo2019
      fonts:
        - asset: assets/fonts/gyobo2019.ttf

    - family: gyobo2020Parkdoyeon
      fonts:
        - asset: assets/fonts/gyobo2020Parkdoyeon.ttf

    - family: gyobo2022kimhyenam
      fonts:
        - asset: assets/fonts/gyobo2022kimhyenam.ttf 

    - family: gyobo2024parkseowoo
      fonts:
        - asset: assets/fonts/gyobo2024parkseowoo.ttf

    - family: MapoFlowerIsland
      fonts:
        - asset: assets/fonts/MapoFlowerIsland.ttf

    - family: ongeulleap_ryuryu
      fonts:
        - asset: assets/fonts/ongeulleap_ryuryu.ttf


